# Generated by Django 3.2.8 on 2021-11-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercisetable',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('muscle', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exerciseTable',
                'managed': False,
            },
        ),
    ]
