# Generated by Django 3.1.6 on 2021-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcfit', '0002_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('rest', models.TextField(blank=True, null=True)),
                ('rir', models.IntegerField(blank=True, null=True)),
                ('load', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workouts',
                'managed': False,
            },
        ),
    ]
