export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

// fat secret token
export const FAT_SECRET_TOKEN_SUCCESS = "FAT_SECRET_TOKEN_SUCCESS";
export const FAT_SECRET_TOKEN_FAILED = "FAT_SECRET_TOKEN_FAIL";

// fat secret search
export const FAT_SECRET_FOOD_SEARCH_SUCCESS = "FAT_SECRET_FOOD_SEARCH_SUCCESS";
export const FAT_SECRET_FOOD_SEARCH_LOADING = "FAT_SECRET_FOOD_SEARCH_LOADING";
export const FAT_SECRET_FOOD_SEARCH_FAILED = "FAT_SECRET_FOOD_SEARCH_FAILED";

// fat secret data
export const FAT_SECRET_FOOD_DATA_ADDING = "FAT_SECRET_FOOD_DATA_ADDING";
export const FAT_SECRET_FOOD_DATA_SUCCESS = "FAT_SECRET_FOOD_DATA_SUCCESS";
export const FAT_SECRET_FOOD_DATA_FAILED = "FAT_SECRET_FOOD_DATA_FAILED";

// nutritions data
export const NUTRITIONS_DATA_LOADING = "NUTRITIONS_DATA_LOADING";
export const NUTRITIONS_DATA_SUCCESS = "NUTRITIONS_DATA_SUCCESS";
export const NUTRITIONS_DATA_FAILED = "NUTRITIONS_DATA_FAILED";

// update data
export const NUTRITIONS_BREAKFAST_DATA_UPDATE =
  "NUTRITIONS_BREAKFAST_DATA_UPDATE";
export const NUTRITIONS_SNACK_DATA_UPDATE = "NUTRITIONS_SNACK_DATA_UPDATE";
export const NUTRITIONS_LUNCH_DATA_UPDATE = "NUTRITIONS_LUNCH_DATA_UPDATE";
export const NUTRITIONS_DINNER_DATA_UPDATE = "NUTRITIONS_DINNER_DATA_UPDATE";
export const MACRO_NUTRITIONS_DATA_UPDATE = "MACRO_NUTRITIONS_DATA_UPDATE";
